### ISSUE TITLE
Suggestions.

### ISSUE THREAD

**Issue by freefreeno** [B00merang-Project/macOS-Dark#14]
I know you are still working. The window buttons are looking good. BUT I didn't think the rest of the theme didn't need much to be perfect and as matter of fact probably just the slider buttons fixed and I really can't remember but not much. The panel in xfce is much too dark and glassy now as well as thunar being a little too dark.I don't know how themes do it but maybe add the little outlines around the the theme edges and the lines in thunar.

**Comment by Elbullazul** [comment]
what do you mean by glassy panel? can you post a screenshot? Some colors changed due to Mojave color scheme, but I believe the colors are brighter

**Comment by freefreeno** [comment]
Ok I am gonna post sceen shots but also when you add a theme to xfce you can see the colors of the theme inside the settings in the appearance section. It has three bars that show you the colors of that particular theme. Well the macOS dark theme is showing a black bar and two white bars and it should only being showing a blue and white and a black bar. That is no big deal BUT if everything is set up correctly inside the theme then the colors would show correctly at that point. Thunar opens at the top left corner of the screen and only time a theme does that to me is if something is off. I have my windows set to open in center of screen. The top part of thunar needs to be matched with your very nice xfwm4 theme. It seems a little off on the color. From the xfwm4 down into thunar at the top where the window manager runs into the the top of thunar. I don't know something just seems off in thunar with the maybe the search bar looking like its setting on top of the theme. The words on a file on my desktop (the name of the file) is really bad blurry.  I am gonna send one screenshot of another theme with same file on desktop and show the words clear also. The xfce panel is just too black so therefore it appears like it has a lot of contrast so it is shiny. Sorry for my bad explanations of stuff. In the screenshots you can see the other themes inside my appearance settings displaying there colors correctly. 
Do unactive windows really need to change color that much.???

[http://imgbox.com/nE4ZF0yc
http://imgbox.com/z8tj26mX
http://imgbox.com/awX8QPyu
http://imgbox.com/Gqh1ZqA5
http://imgbox.com/rvrKbPsc](url)

Over all you've made great progress. Main thing are the things I mentioned. One last thing you have the open windows highlighted in blue on my panel. That would look better in grey.You will see in the screenshots. You have the best xfwm4 theme I can find now. The way you do the xfwm4 theme gives it that rolled back look and it looks good. There are some screenshots of just stuff to show you like the whisker menu in the last set of screenshots. 
[http://imgbox.com/vqnJYEkg
http://imgbox.com/9yhkHUxq](url)

**Comment by Elbullazul** [comment]
last time I had checked (yosemite) macos had dark panels, hadn't realized Mojave had nuanced it more. 
panel higlight however is compliant to mojave look:

![image](https://user-images.githubusercontent.com/15310985/53307024-faaaee00-3861-11e9-89ca-d284be75595b.png)

contextual menus and chrome bookmarks are the same issue, menu bg coloring.
I removed forced placement, didn't know it had any real effect (almost never use xfce).
notifications have not been patched since 2017, so I think the current theme is outdated or isn't relevant.
preview colors are probably due to the gtk2 theme being pixbuf based. I'm planning on going back to murrine rendering but can't say when
I don't have desktop icon text shadow issue on linux mint 19.1
can't test pamac as I don't use arch, but can probably be patched with minor changes

I can't put too much effort this week since I have exams, but I'll try to patch whenever I can

Regards,

**Comment by Elbullazul** [comment]
menus are now more distinct: 
![image](https://user-images.githubusercontent.com/15310985/53307722-59c03100-3869-11e9-80ca-b0268823fe08.png)
notification themes seem to be deprecated or something, they won't show up in notification settings
color preview was due to colors being declared outside of gtkrc. fixed it by merging colors.rc and gtkrc
changed the panel color to #b3b3b3
edited the logout dialog to remove the previously used asset
removed the icon shadow issue

**Comment by freefreeno** [comment]
You  have to make notification themes like this. You place a folder named xfce-notify-4.0 in main theme folder.
![screenshot_2019-02-25_10-12-19](https://user-images.githubusercontent.com/41884680/53351319-ae55c180-38e6-11e9-92ee-538f82fea04a.png)

Inside are three files like this.

![screenshot_2019-02-25_10-12-30](https://user-images.githubusercontent.com/41884680/53351456-f4128a00-38e6-11e9-9ebe-baf24632be96.png)

They are these files. gtk.css
![gtkcss](https://user-images.githubusercontent.com/41884680/53351513-055b9680-38e7-11e9-9a25-30ab0caec967.png)

And gtkrc
![gtkrc](https://user-images.githubusercontent.com/41884680/53351603-2c19cd00-38e7-11e9-9b4c-d4b3fd6038d6.png)


And xfce-notify.rc
![xfce-notifyrc](https://user-images.githubusercontent.com/41884680/53351883-700cd200-38e7-11e9-9687-5641cd3eff5b.png)
 This is the only way your theme will have a pure notification theme that we can choose to use in our settings. I see you added the folder but it doesn't show up in the settings. I do believe it has to have all three files.

**Comment by Elbullazul** [comment]
It appears notifications are themed by GTK3 rules. d884243 and e9e74262aa4b6bf6788f1f5a9d9dc479d2616ff9 fix this
